"""five

Revision ID: 88944f0dd7c2
Revises: 4bcc8456f051
Create Date: 2025-06-13 14:14:52.280985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88944f0dd7c2'
down_revision = '4bcc8456f051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
