"""add unique constraint on user_id and country_id

Revision ID: b9db5461ea06
Revises: 5ef9e7734aeb
Create Date: 2025-06-17 06:23:43.804078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9db5461ea06'
down_revision = '5ef9e7734aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_country', 'reviews', ['user_id', 'country_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_country', 'reviews', type_='unique')
    # ### end Alembic commands ###
