"""eight

Revision ID: e6a5d4aef9eb
Revises: 42cff5d49174
Create Date: 2025-06-14 18:13:08.015434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a5d4aef9eb'
down_revision = '42cff5d49174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
